"""initial schema

Revision ID: 86ed567552da
Revises: 
Create Date: 2026-03-08 03:06:22.316841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ed567552da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hive_agents',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('caste', sa.Enum('queen', 'scout', 'worker', 'guard', 'drone', name='caste'), nullable=False),
    sa.Column('state', sa.Enum('booting', 'idle', 'assigned', 'executing', 'reporting', 'blocked', 'quarantined', 'retired', name='agentstate'), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('sandbox_profile', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('hive_tasks',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'triaged', 'planned', 'assigned', 'active', 'review', 'done', 'blocked', 'rejected', 'archived', name='taskstate'), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('deps_json', sa.JSON(), nullable=False),
    sa.Column('assigned_json', sa.JSON(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('hive_artifacts',
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('producer_agent_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['hive_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('hive_signals',
    sa.Column('signal_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('opportunity', 'warning', 'completion', 'failure', 'resource', name='signalkind'), nullable=False),
    sa.Column('source_agent_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('estimated_cost_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['hive_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hive_signals')
    op.drop_table('hive_artifacts')
    op.drop_table('hive_tasks')
    op.drop_table('hive_agents')
    op.drop_table('agent_roles')
    # ### end Alembic commands ###
